Bugfix estimate km
openpharma/visR pull request #119
Opened 2021-03-05 12:38 UTC by rebecca-albrecht

2021-03-05 13:18 UTC, SHAESEN2 requested changes
Nice catch, but you are repeating the same testing in two different pull requests. Can you update in one and then OK for me to merge this one.

2021-03-05 13:50 UTC, SHAESEN2 requested changes
If you prefer we can have a call.

2021-03-05 13:50 UTC, SHAESEN2 commented on tests/testthat/test-estimate_KM.R
> +#' T2.1 An error when colname specified as analysis value is not present in `data`
keep AVAL

2021-03-05 13:50 UTC, SHAESEN2 commented on tests/testthat/test-estimate_KM.R
> +#' T2.2 An error when colname specified as analysis value is not numeric
Keep AVAL

2021-03-05 13:50 UTC, SHAESEN2 commented on tests/testthat/test-estimate_KM.R
> +#' T2.3 An error when `AVAL` is not the actual column used as analysis value and this column is not numeric
It is still unclear. Can't you keep AVAL is not numeric. Does not really matter how the column is called. You are testing the paramter => use parameter as column => is corresponding column numeric

2021-03-05 13:50 UTC, SHAESEN2 commented on tests/testthat/test-estimate_KM.R
> +#' T2.4 An error when colname specified as censor value is not present in `data`
keep CNSR

2021-03-05 13:50 UTC, SHAESEN2 commented on tests/testthat/test-estimate_KM.R
> +#' T2.5 An error when colname specified as censor value is not numeric
Keep CNSR

2021-03-05 13:50 UTC, SHAESEN2 commented on tests/testthat/test-estimate_KM.R
> +#' T2.6 An error when `CNSR` is not the actual column used as censor value and this column is not numeric
See AVAL comment

2021-03-05 13:56 UTC, rebecca-albrecht commented
Ok, I guess I don't get it Steven, I am sorry! Do you mean that the tests of the estimate_km are in both branches?

Unfortunately, I cannot have a call now. I have to pick up the kids. I will check in again later tonight!

2021-03-06 07:18 UTC, SHAESEN2 commented
Still updates required. I will create a new pull request.

2021-03-06 07:18 UTC, closed without merging