update s3 methods to be consistent
openpharma/visR pull request #172
Opened 2021-05-09 20:53 UTC by bailliem

update s3 methods to be consistent
* risktables
* get_quantile
* get_summary
* get_COX_HR

changed files so object class = x and ensure that ... was present in function call for S3 methods

2021-05-11 05:49 UTC, bailliem commented
Close. Rename plot function to visr

2021-05-11 05:53 UTC, bailliem commented
Wrong pr closed

2021-05-21 06:13 UTC, SHAESEN2 requested changes
Can you pull in develop and make sure all the test pass as well?

2021-05-21 06:13 UTC, SHAESEN2 commented on R/get_COX_HR.R
> +#' @param x An object of class \code{survfit_visr}
This needs to be changed back to survfit.

2021-05-22 18:13 UTC, bailliem reviewed
Removed visr from survfit object reference

2021-05-22 18:13 UTC, merged