Renamed summary functions for table 1
openpharma/visR pull request #197
Opened 2021-05-30 08:03 UTC by cschaerfe

2021-05-30 08:06 UTC, cschaerfe commented
not quite ready to merge. I still need to update the documentation

2021-05-30 10:47 UTC, SHAESEN2 requested changes

2021-05-30 10:47 UTC, SHAESEN2 commented on R/get_tableone.R
> +#'
remove library call from examples

2021-05-30 10:47 UTC, SHAESEN2 commented on R/tableone.R
> +#'
remove lib calls

2021-05-30 10:47 UTC, SHAESEN2 commented on tests/testthat/test-utils_table.R
> +#' T1. Correct values for summarize_long.numeric
define correct

2021-05-30 19:40 UTC, cschaerfe commented on R/get_tableone.R
> +#'
done

2021-05-30 19:40 UTC, cschaerfe commented on R/tableone.R
> +#'
done

2021-05-30 19:41 UTC, cschaerfe commented on tests/testthat/test-utils_table.R
> +#' T1. Correct values for summarize_long.numeric
correct is defined in the subtasks

2021-05-30 19:43 UTC, cschaerfe commented
@timtreis , @SHAESEN2 , @bailliem - I think I'm done here now. Please merge whenever you found time to review

2021-05-31 08:02 UTC, SHAESEN2 approved these changes

2021-05-31 08:53 UTC, merged